import type { ProductDetail } from "./types";

export const MOCK_PRODUCT: ProductDetail = {
  id: "immortal-level-500",
  title: "Level 500+ Valorant Account - Immortal Rank",
  tags: [
    { label: "Instant Delivery", variant: "primary" },
    { label: "Full Access", variant: "secondary" },
    { label: "Region: NA", variant: "secondary" },
  ],
  rating: 5.0,
  reviewCount: 124,
  price: 149.99,
  originalPrice: 299.0,
  discountPercent: 50,
  isVerifiedSeller: true,
  images: [
    {
      url: "https://lh3.googleusercontent.com/aida-public/AB6AXuC8BB4Vr4BzTHlFnwADRs8TGW_ZWQwtHAz0fNRwanyylouCcgwcz4w7h2VcAHX-BbOJdIvZKnk7874Mo-JomD6Poweabn3FwKGS2zM7M8eiL93JKs2eWQKG5NF6lI3jeyHg_byGfNsROievnHW0tJnffeNdOoiwS64wJTF5MgU0Piv6ZWJkM4cqR10bYmogtsSuUtPWyuWEiEvKYvIb9SiveB_iFu6qrbPsq4T5E3FPndcrOC9c3SI_qirvz2byQBg1rVGMexzhjKE",
      alt: "Main showcase of a high-level Valorant game account profile with rare skins",
    },
    {
      url: "https://lh3.googleusercontent.com/aida-public/AB6AXuBUzryXkCOIQBTtOVBOnfwPGWIw2WX1dlhKwg6O1Vhoow4lEr5Tr0mllaQsPBv9FS14OAk_22FZHZyJbtoRASi1CnDqVadW38_Ik7Dc--rn5TEZF2wHl1AYpJ70gVKWIx8z4D_XNIfaP2iWNHQUIKfLc71DX3QWAj7ye60REYVEheRnVcmRbgCZ1jOrgqKMuIc6-le7hle7jN5XBGcxau92yqMUjwqlWd4GQM455u_KYTD0T59l2oNzTnWBA2jW-7jTkonIjS4-y1c",
      alt: "Screenshot of inventory showing various weapon skins",
    },
    {
      url: "https://lh3.googleusercontent.com/aida-public/AB6AXuAeaeM6IL0VTjLtubQDlwgI08IOAgnzTQtbTQzQEzQvn3zTE96HPN-z-eFjrK_zs57QGerzpsg7C_z5_qSx9_YmJyBFib7SVlPnIiv0lLrhb5Q_ORzPfmc-hCj9MCNvzkCP8tU-Is5SLev_g_Xm9VvFy_jbMX9-4t4QwlOsNJ2HFTgYoW4vrT5XOsRF_ISM2NeNKSGd76oCBWkIGSRv8uSBKWxXOvVFPIjYi6VFYuha_ujL8SiQaHlxe5B_Q_Mj6AFs3VArBwxkIL4",
      alt: "Screenshot of character selection screen showing unlocked agents",
    },
    {
      url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCIKk_8NQWCayE6jgSX5FMQE754UW6yhns0G4KfswxphcLdlUgtfGGua9hT5hhvZkIoquxjiULEqjhdthoIFaCwmbsCYd4A-08Io_L-lDNnI_jXeFWOIig5Ei_5UldycDAKmtYGXUFWGvbGGT4FNQNJoGfpWwuVGv0R7C30XHoe03kL2y6UtotyjzHD0XsXZYlKKebwkIw52HsRJiVJejvafjsOV7d3CynMDWoxrnkGoMBdU_3gN7JjcQwWZy0xvlNxjBd4O3cnI28",
      alt: "Screenshot of competitive career stats and rank",
    },
  ],
  stats: [
    {
      id: "rank",
      label: "Rank",
      value: "Immortal 3",
      icon: "military_tech",
      iconBg: "bg-red-100",
      iconColor: "text-red-500",
    },
    {
      id: "level",
      label: "Level",
      value: "524",
      icon: "award_star",
      iconBg: "bg-blue-100",
      iconColor: "text-blue-500",
    },
    {
      id: "skins",
      label: "Skins",
      value: "142 Premium",
      icon: "palette",
      iconBg: "bg-purple-100",
      iconColor: "text-purple-500",
    },
    {
      id: "winrate",
      label: "Win Rate",
      value: "58.4%",
      icon: "trending_up",
      iconBg: "bg-green-100",
      iconColor: "text-green-500",
    },
    {
      id: "inventory",
      label: "Inventory Value",
      value: "~$800",
      icon: "attach_money",
      iconBg: "bg-yellow-100",
      iconColor: "text-yellow-600",
    },
  ],
  description: `This Immortal 3 account is a prime choice for players looking to jump straight into high-elo gameplay. It features a massive collection of premium skins including the Elderflame Bundle, Reaver Vandal, and Ion Phantom. The account has been hand-leveled with a clean history and no bans.\n\nWith a high win rate over the last 3 acts, your MMR is set for success. Full email access is provided instantly upon purchase, allowing you to change the password and secure the account immediately.`,
  highlights: [
    "All Agents Unlocked",
    "Battlepass Completed for last 3 Acts",
    "Current Act Rank: Immortal 3 (300RR)",
    "Region Change Available",
  ],
  specifications: [
    { key: "Game", value: "Valorant" },
    { key: "Rank", value: "Immortal 3 (300RR)" },
    { key: "Account Level", value: "524" },
    { key: "Region", value: "North America (NA)" },
    { key: "Email Access", value: "Full Access Included" },
    { key: "Premium Skins", value: "142" },
    { key: "Agents Unlocked", value: "All Agents" },
    { key: "Win Rate", value: "58.4%" },
    { key: "Inventory Value", value: "~$800" },
    { key: "Account History", value: "Clean — No Bans" },
    { key: "Delivery Method", value: "Instant Email Delivery" },
    { key: "Warranty", value: "Lifetime Warranty" },
  ],
  reviews: [
    {
      id: "review-1",
      author: "Alex M.",
      avatarGradient: "from-primary to-blue-600",
      rating: 5,
      date: "2 days ago",
      body: "Instant delivery as promised! The skins are amazing and the rank is legit. Highly recommend this seller.",
    },
    {
      id: "review-2",
      author: "Sarah K.",
      avatarGradient: "from-green-500 to-emerald-700",
      rating: 5,
      date: "1 week ago",
      body: "Everything worked perfectly. Changed email and password immediately without issues.",
    },
  ],
  overallRating: 4.9,
  breadcrumb: [
    { label: "Home", href: "/" },
    { label: "Valorant Accounts", href: "/products" },
    { label: "Immortal Rank / Level 500+" },
  ],
  similarProducts: [
    {
      id: "ascendant-2-full-skins",
      title: "Ascendant 2 - Full Skins",
      subtitle: "NA Region • Hand Leveled",
      imageUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuBR1f7Av1z4T1CilQYKXwvWYzTRkpyc9MLMtVFQc83_VUmYb4GGRmSWOzFyhXPVfuaEOvHH3d_gwkbT8H83QhqxeS8-tDRi9-BnpLaenCIa30JH12EJxiUfexVQja-NuNgsIZ3gYTQ8jRsNqpU6t8KO8peTRFBTvBTUl9m4N-RTS8M8riQ7aFVf3VmaJfExc37AyU_1HDFf6KiPtwUghitUZe9Pm87ddc62w1E-KL9ke0Q3gIBQu25QvmO3KUSkraKg4o58mGnOvLU",
      imageAlt: "Abstract colorful geometric pattern representing a game account cover",
      level: 300,
      price: 89.99,
    },
    {
      id: "immortal-1-reaver-set",
      title: "Immortal 1 - Reaver Set",
      subtitle: "EU Region • Verified",
      imageUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuD_ybGboJ1a2aiWPtw_oMrdmTOra5NL6G2uaCJa6JyKADJJ7Zw0SzXSSfU1VBKeY1D_Lj40YsImbK_87RPk0MUt8wZZVqa_Gi3kKZmEBpiQLN1uQsnkJKXB9I0OYRYmqJv_w5z-WQ05n6UIs1lPTqyS22woAR7B5CUFmspQ5gGCdFIVn_Uq1o2Y7Ybs1cEKQpE1FRTBsv3YWkIR-X7kdCf-e2DUL3YQ3eEPCYhsr0rzVeKHN8aIkycmgJR41oVB8FKnLJrtLO49Vsg",
      imageAlt: "Dark purple abstract digital art background",
      level: 450,
      price: 119.99,
    },
    {
      id: "diamond-3-smurf",
      title: "Diamond 3 Smurf",
      subtitle: "NA Region • 20 Skins",
      imageUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuCt-hJkqchzimSHfm-GGUVwLlcX8w_rsbPaQ-Or5T1EFfQgnWgpFYoHG5FK4DmWtw1uag4n6UvFv0lBVdrefIcTIU1Udhy8mKamBgy8_zH1oUzyjc6x6TKLnQR35GMh4nS8UoSVRSf72CakeamJKoIj96srzCJT6cLB9Bcrtmjpr4m3_1AAtv7-r4X4JwxJNYkg0Fva13UZCrEylua6sQjhgjVTb6foQf08yIo7F9v6gz4m-UY_my8wARM-XIWvIBJHSXxsbexola4",
      imageAlt: "Neon blue and pink gradient gaming style background",
      level: 120,
      price: 45.0,
    },
    {
      id: "radiant-peak-account",
      title: "Radiant Peak Account",
      subtitle: "KR Region • Rare Items",
      imageUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuDzs10SaCkMfWa6Sb8J-TXAdwrz6bz-XfkwBMOOPhtgqrEJFNAnBVVcM1tfJ216-UqfrsuQ6UMb_YCG5SAZKXNetU-I94dZAn3JH2aBQkJncaSmq_bX3OrPuDXlCjVdiL_CmPuZEg6Ha_71aZXvHtCki0oE_Jf3TxekJHnKHEN3mDQY9VH9KZaBJ2GJrje5NU8PwinbLTaKuMit-N9YEtMzV1gjxIMiceO5iNQaPkUQLzsBcjTp8eyxWbsmID4FkMfYtMl53loX7gI",
      imageAlt: "Red and black abstract gaming background",
      level: 890,
      price: 499.99,
    },
  ],
};
