module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#7C3AED", // Distinct purple from screenshots
        "primary-hover": "#6D28D9",
        "background-light": "#F3F4F6",
        "background-dark": "#18181B", // Dark zinc
        "surface-light": "#FFFFFF",
        "surface-dark": "#27272A", // Slightly lighter dark
        "accent-dark": "#1F1F23", // Deep background for sections
        "primary-dark": "#6a0ec6",
        "border-light": "#e0dbe6",
        "border-dark": "#3b2d4a",
        "on-tertiary-container": "#290055",
        "on-secondary": "#ffffff",
        "surface-bright": "#ffffff",
        "on-primary-fixed-variant": "#6200bc",
        "primary-container": "#7f13ec",
        "outline-variant": "#f2f0f4",
        "surface-container-high": "#e0dbe6",
        "surface-container-low": "#fcfbfc",
        "on-error": "#ffffff",
        "secondary": "#141118",
        "on-tertiary": "#ffffff",
        "on-surface": "#141118",
        "surface-tint": "#7f13ec",
        "tertiary-fixed": "#ffdbc8",
        "secondary-container": "#f2f0f4",
        "surface-container": "#f2f0f4",
        "inverse-surface": "#342e3a",
        "background": "#f7f6f8",
        "tertiary-container": "#eddcff",
        "tertiary-fixed-dim": "#ffb68b",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#753400",
        "inverse-primary": "#d8b9ff",
        "tertiary": "#7249a9",
        "on-secondary-container": "#141118",
        "on-background": "#141118",
        "on-secondary-fixed-variant": "#756189",
        "secondary-fixed": "#f2f0f4",
        "on-tertiary-fixed": "#321200",
        "on-primary-fixed": "#290055",
        "on-secondary-fixed": "#141118",
        "secondary-fixed-dim": "#e0dbe6",
        "on-primary": "#ffffff",
        "surface-dim": "#f7f6f8",
        "primary-fixed": "#eddcff",
        "primary-fixed-dim": "#d8b9ff",
        "surface": "#ffffff",
        "on-primary-container": "#ffffff",
        "surface-container-highest": "#141118",
        "outline": "#e0dbe6",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface-variant": "#f2f0f4",
        "on-surface-variant": "#756189",
        "inverse-on-surface": "#f8edfd",
      },
      fontFamily: {
        display: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        xl: "1rem",
        lg: "1rem",
      },
    },
  },
};
